import Foundation
import System
import SwiftParser
import SwiftSyntax
import SwiftSyntaxBuilder
import Logging

extension InitCommand {
    protocol SwiftSyntaxTask {}
}

extension InitCommand.SwiftSyntaxTask {
    func loadSourceFileSyntax(for path: FilePath) throws -> SourceFileSyntax {
        let url = URL(filePath: path)!
        let content = try String(contentsOf: url, encoding: .utf8)
        return Parser.parse(source: content)
    }

    func writeSourceFileSyntax(_ source: some SyntaxProtocol, to path: FilePath) throws {
        let url = URL(filePath: path)!
        let content = source.formatted().description
        try content.write(to: url, atomically: true, encoding: .utf8)
    }
}

extension InitCommand {
    struct RegionFilter<C: SyntaxCollection> {
        enum MarkerPosition {
            case begin, end
        }

        private var checkMarker: (TriviaPiece) -> MarkerPosition?

        init(_ checkMarker: @escaping (TriviaPiece) -> MarkerPosition?) {
            self.checkMarker = checkMarker
        }

        func findMarker(_ trivia: Trivia) -> MarkerPosition? {
            trivia.lazy.compactMap(checkMarker).first
        }

        func findMarker(_ piece: TriviaPiece) -> MarkerPosition? {
            checkMarker(piece)
        }

        @specialized(where C == ArrayElementListSyntax)
        @specialized(where C == CodeBlockItemListSyntax)
        func callAsFunction(_ collection: C) -> (passed: [C.Element], filtered: [C.Element]) {
            var passed: [C.Element] = []
            var filtered: [C.Element] = []
            var isInAutoGeneratedCode = false

            for item in collection {
                func shouldPass() -> Bool {
                    let position = findMarker(item.leadingTrivia)
                    if position == .begin {
                        isInAutoGeneratedCode = true
                        return false
                    }
                    if position == .end {
                        isInAutoGeneratedCode = false
                        return false
                    }
                    return !isInAutoGeneratedCode
                }

                if shouldPass() {
                    passed.append(item)
                } else {
                    filtered.append(item)
                }
            }
            return (passed, filtered)
        }
    }
}
