import System
import SwiftSyntax

struct InsertSettingAndPluginTask: SwiftSyntaxTask {
    var packagePath: FilePath
    var swiftSettings: [Config.SwiftSetting]
    var hasSwiftFormatPlugin: Bool

    private let beginMarker = "BEGIN AUTO GENERATED: swift-project-starter: settings"
    private let endMarker = "END AUTO GENERATED: swift-project-starter: settings"

    func run() async throws {
        var source = try loadSourceFileSyntax(for: packagePath)
        source = removingInsertionCode(from: source)

        let code = try makeInsertionCode()
            .with(\.leadingTrivia, [.newlines(2), .lineComment("// \(beginMarker)"), .newlines(1)])
            .with(\.trailingTrivia, [.newlines(1), .lineComment("// \(endMarker)")])

        var statements = source.statements
        statements.append(contentsOf: code)
        let result = source.with(\.statements, statements)

        try writeSourceFileSyntax(result, to: packagePath)
    }

    private func removingInsertionCode(from source: SourceFileSyntax) -> SourceFileSyntax {
        func hasMarker(_ trivia: Trivia, marker: String) -> Bool {
            trivia.contains {
                if case .lineComment(let text) = $0 {
                    return text.hasPrefix("// \(marker)")
                }
                return false
            }
        }

        var statements: [CodeBlockItemSyntax] = []
        var isInAutoGeneratedCode = false

        for item in source.statements {
            if hasMarker(item.leadingTrivia, marker: beginMarker) {
                isInAutoGeneratedCode = true
                continue
            }
            if hasMarker(item.leadingTrivia, marker: endMarker) {
                isInAutoGeneratedCode = false
                continue
            }
            if isInAutoGeneratedCode {
                continue
            }

            statements.append(item)
        }
        let endTrivia = source.endOfFileToken.leadingTrivia
        let foundEndMarker = isInAutoGeneratedCode && hasMarker(endTrivia, marker: endMarker)

        return
            source
            .with(\.statements, CodeBlockItemListSyntax(statements))
            .with(\.endOfFileToken.leadingTrivia, foundEndMarker ? .newline : endTrivia)
    }

    private func makeInsertionCode() throws -> CodeBlockItemListSyntax {
        return try CodeBlockItemListSyntax {
            try ForStmtSyntax("for target in package.targets") {
                try IfExprSyntax("if [.executable, .test, .regular].contains(target.type)") {
                    try DoStmtSyntax("do") {
                        let settings = ArrayElementListSyntax {
                            for setting in swiftSettings {
                                ArrayElementSyntax(expression: setting.toSyntax())
                                    .with(\.leadingTrivia, .newline)
                            }
                        }.with(\.trailingTrivia, .newline)

                        "var swiftSettings = target.swiftSettings ?? []"
                        "defer { target.swiftSettings = swiftSettings }"
                        "swiftSettings += [\(settings)]"
                    }

                    if hasSwiftFormatPlugin {
                        try DoStmtSyntax("do") {
                            let plugins = ArrayElementListSyntax {
                                let plugin = ExprSyntax(
                                    """
                                    .plugin(name: "Lint", package: "swift-format-plugin")
                                    """)
                                ArrayElementSyntax(expression: plugin)
                                    .with(\.leadingTrivia, .newline)
                            }.with(\.trailingTrivia, .newline)

                            "var plugins = target.plugins ?? []"
                            "defer { target.plugins = plugins }"
                            "plugins += [\(plugins)]"
                        }
                    }
                }
            }
        }
    }
}

private extension Config.SwiftSetting {
    func toSyntax() -> ExprSyntax {
        switch self {
        case .defaultIsolation(let isolation):
            return ExprSyntax(".defaultIsolation(\(raw: isolation.rawValue).self)")

        case .enableUpcomingFeature(let feature):
            return ExprSyntax(".enableUpcomingFeature(\"\(raw: feature)\")")

        case .enableExperimentalFeature(let feature):
            return ExprSyntax(".enableExperimentalFeature(\"\(raw: feature)\")")
        }
    }
}
