import System
import SwiftSyntax
import Logging

struct InstallDependencyTask: SwiftSyntaxTask {
    var dependencies: [Config.Dependency]
    var packagePath: FilePath

    private static let beginMarker = "BEGIN AUTO GENERATED: swift-project-starter: deps"
    private static let endMarker = "END AUTO GENERATED: swift-project-starter: deps"

    func run() async throws {
        let source = try loadSourceFileSyntax(for: packagePath)

        let result = DepsRewriter(dependencies: dependencies).rewrite(source)
        try writeSourceFileSyntax(result, to: packagePath)
    }

    private class DepsRewriter: SyntaxRewriter {
        let dependencies: [Config.Dependency]

        init(dependencies: [Config.Dependency]) {
            self.dependencies = dependencies
            super.init()
        }

        override func visit(_ node: FunctionCallExprSyntax) -> ExprSyntax {
            // find Package(...)
            guard let called = node.calledExpression.as(DeclReferenceExprSyntax.self),
                called.baseName.trimmed.text == "Package"
            else {
                return super.visit(node)
            }

            guard
                let argIndex = node.arguments.firstIndex(where: {
                    $0.label?.trimmed.text == "dependencies"
                })
            else {
                return super.visit(node)
            }

            let rewriter = AutoGeneratedDependencyRemover()
            let deps =
                rewriter
                .rewrite(node.arguments[argIndex])

            var dependencies = dependencies
            var insertedPackages = rewriter.insertedPackages

            // cleaning existing dependencies
            for (index, pkg) in insertedPackages.enumerated().reversed() {
                let status = checkExistingStatus(for: pkg, in: &dependencies)
                switch status {
                case .removed, .exists, .missing:
                    insertedPackages.remove(at: index)

                case .modified(let cleaned):
                    insertedPackages[index] = cleaned
                }
            }

            // insert dependencies
            guard
                let deps =
                    AutoGeneratedDependencyInserter(insertedPackages: insertedPackages, dependencies: dependencies)
                    .rewrite(deps)
                    .as(LabeledExprSyntax.self)
            else {
                return super.visit(node)
            }

            return super.visit(node.with(\.arguments[argIndex], deps))
        }

        private enum ExistingStatus {
            case missing
            case removed
            case exists
            case modified(cleaned: FunctionCallExprSyntax)
        }

        private func checkExistingStatus(for expr: FunctionCallExprSyntax, in deps: inout [Config.Dependency])
            -> ExistingStatus
        {
            func extractValue(forKey key: String) -> String? {
                expr.arguments
                    .first(where: { $0.label?.trimmed.text == key })?
                    .expression
                    .as(StringLiteralExprSyntax.self)?
                    .segments
                    .trimmedDescription
            }

            guard let url = extractValue(forKey: "url") else {
                return .missing
            }

            for (index, dep) in deps.enumerated().reversed() where dep.url == url {
                guard
                    let from = extractValue(forKey: "from"),
                    from == dep.from
                else {
                    let cleaned = TriviaRemover()
                        .rewrite(expr)
                        .cast(FunctionCallExprSyntax.self)
                    deps.remove(at: index)
                    Logger.currentScope?.warning("skipping dependency: \(url)")
                    return .modified(cleaned: cleaned)
                }
                return .exists
            }

            return .removed
        }

        struct RegionFilter<C: SyntaxCollection> {
            enum MarkerPosition {
                case begin, end
            }

            var checkMarker: (TriviaPiece) -> MarkerPosition?

            @specialized(where C == ArrayElementListSyntax)
            func callAsFunction(_ collection: C) -> (passed: [C.Element], filtered: [C.Element]) {
                func findMarker(_ trivia: Trivia) -> MarkerPosition? {
                    trivia.lazy.compactMap(checkMarker).first
                }

                var passed: [C.Element] = []
                var filtered: [C.Element] = []
                var isInAutoGeneratedCode = false

                for item in collection {
                    func shouldPass() -> Bool {
                        let position = findMarker(item.leadingTrivia)
                        if position == .begin {
                            isInAutoGeneratedCode = true
                            return false
                        }
                        if position == .end {
                            isInAutoGeneratedCode = false
                            return false
                        }
                        return !isInAutoGeneratedCode
                    }

                    if shouldPass() {
                        passed.append(item)
                    } else {
                        filtered.append(item)
                    }
                }
                return (passed, filtered)
            }
        }

        private class AutoGeneratedDependencyRemover: SyntaxRewriter {
            private(set) var insertedPackages: [FunctionCallExprSyntax] = []

            override func visit(_ node: ArrayExprSyntax) -> ExprSyntax {
                let filter = RegionFilter<ArrayElementListSyntax> { trivia in
                    if case .lineComment(let string) = trivia {
                        if string.hasPrefix("// \(beginMarker)") {
                            return .begin
                        }
                        if string.hasPrefix("// \(endMarker)") {
                            return .end
                        }
                    }
                    return nil
                }

                let (passed, filtered) = filter(node.elements)
                insertedPackages.append(
                    contentsOf: filtered.compactMap {
                        $0.expression.as(FunctionCallExprSyntax.self)
                    }
                )

                let pieces = node.rightSquare.leadingTrivia.filter { filter.checkMarker($0) == nil }
                let newNode =
                    node
                    .with(\.elements, .init(passed))
                    .with(\.rightSquare.leadingTrivia, Trivia(pieces: pieces))
                return super.visit(newNode)
            }
        }

        private class AutoGeneratedDependencyInserter: SyntaxRewriter {
            var insertedPackages: [FunctionCallExprSyntax]
            var dependencies: [Config.Dependency]

            init(insertedPackages: [FunctionCallExprSyntax], dependencies: [Config.Dependency]) {
                self.insertedPackages = insertedPackages
                self.dependencies = dependencies
                super.init()
            }

            override func visit(_ node: ArrayExprSyntax) -> ExprSyntax {
                guard !insertedPackages.isEmpty || !dependencies.isEmpty else {
                    return super.visit(node)
                }

                defer {
                    insertedPackages = []
                    dependencies = []
                }

                var elements: [ArrayElementSyntax] = []
                for pkg in insertedPackages {
                    elements.append(
                        ArrayElementSyntax(expression: pkg)
                            .with(\.leadingTrivia, .newline)
                    )
                }
                for dep in dependencies {
                    let expr = ExprSyntax(
                        """
                        .package(url: "\(raw: dep.url)", from: "\(raw: dep.from)")
                        """)
                    elements.append(
                        ArrayElementSyntax(expression: expr)
                            .with(\.leadingTrivia, .newline)
                    )
                }

                if let elem = elements.first {
                    elements[elements.startIndex] =
                        elem
                        .with(
                            \.leadingTrivia,
                            elem.leadingTrivia.appending([.lineComment("// \(beginMarker)"), .newlines(1)]),
                        )
                }

                return super.visit(
                    node
                        .with(\.elements, node.elements + elements)
                        .with(
                            \.rightSquare.leadingTrivia,
                            [.newlines(1), .spaces(4 * 2), .lineComment("// \(endMarker)"), .newlines(1), .spaces(4)],
                        )
                )
            }
        }

        private class TriviaRemover: SyntaxRewriter {
            override func visitAny(_ node: Syntax) -> Syntax? {
                node.trimmed
            }
        }
    }
}
