import SystemPackage
import SwiftSyntax
import Logging

private let beginMarker = "AUTO GENERATED ↓: swift-project-starter: deps"
private let endMarker = "AUTO GENERATED ↑: swift-project-starter: deps"

extension InitCommand {
    struct InstallDependencyTask: InitCommand.SwiftSyntaxTask {
        var dependencies: [Config.Dependency]
        var packagePath: FilePath

        func run() async throws {
            let source = try loadSourceFileSyntax(for: packagePath)

            let result = DepsRewriter(dependencies: dependencies).rewrite(source)
            try writeSourceFileSyntax(result, to: packagePath)
        }
    }
}

private class DepsRewriter: SyntaxRewriter {
    private struct Dependency {
        var value: Config.Dependency
        var exists: FunctionCallExprSyntax?
        var isModified: Bool = false
    }

    private let dependencies: [Dependency]

    init(dependencies: [Config.Dependency]) {
        self.dependencies = dependencies.map {
            Dependency(value: $0)
        }
        super.init()
    }

    override func visit(_ node: FunctionCallExprSyntax) -> ExprSyntax {
        // find Package(...)
        guard
            let called = node.calledExpression.as(DeclReferenceExprSyntax.self),
            called.baseName.trimmed.text == "Package"
        else {
            return super.visit(node)
        }

        guard
            let argIndex = node.arguments.firstIndex(where: {
                $0.label?.trimmed.text == "dependencies"
            })
        else {
            return super.visit(node)
        }

        let rewriter = AutoGeneratedDependencyRemover()
        let dependenciesSection =
            rewriter
            .rewrite(node.arguments[argIndex])

        var dependencies = dependencies

        // cleaning existing dependencies
        for pkg in rewriter.insertedPackages {
            updateExistingDependency(&dependencies, with: pkg)
        }

        // insert dependencies
        guard
            let dependenciesSection =
                AutoGeneratedDependencyInserter(dependencies: dependencies)
                .rewrite(dependenciesSection)
                .as(LabeledExprSyntax.self)
        else {
            return super.visit(node)
        }

        return super.visit(node.with(\.arguments[argIndex], dependenciesSection))
    }

    private func updateExistingDependency(_ deps: inout [Dependency], with expr: FunctionCallExprSyntax) {
        func extractValue(forKey key: String) -> String? {
            expr.arguments
                .first(where: { $0.label?.trimmed.text == key })?
                .expression
                .as(StringLiteralExprSyntax.self)?
                .segments
                .trimmedDescription
        }

        guard let url = extractValue(forKey: "url") else {
            return
        }

        for (index, dep) in deps.enumerated() where dep.value.url == url {
            deps[index].exists = expr
            deps[index].isModified = extractValue(forKey: "from") != dep.value.from
        }
    }

    private class AutoGeneratedDependencyRemover: SyntaxRewriter {
        private(set) var insertedPackages: [FunctionCallExprSyntax] = []

        override func visit(_ node: ArrayExprSyntax) -> ExprSyntax {
            let filter = InitCommand.RegionFilter<ArrayElementListSyntax> { trivia in
                if case .lineComment(let string) = trivia {
                    if string.hasPrefix("// \(beginMarker)") {
                        return .begin
                    }
                    if string.hasPrefix("// \(endMarker)") {
                        return .end
                    }
                }
                return nil
            }

            let (passed, filtered) = filter(node.elements)
            insertedPackages.append(
                contentsOf: filtered.compactMap {
                    $0.expression.as(FunctionCallExprSyntax.self)
                }
            )

            let pieces = node.rightSquare.leadingTrivia.filter { filter.findMarker($0) == nil }
            let newNode =
                node
                .with(\.elements, .init(passed))
                .with(\.rightSquare.leadingTrivia, Trivia(pieces: pieces))
            return super.visit(newNode)
        }
    }

    private class AutoGeneratedDependencyInserter: SyntaxRewriter {
        var dependencies: [Dependency]

        init(dependencies: [Dependency]) {
            self.dependencies = dependencies
            super.init()
        }

        override func visit(_ node: ArrayExprSyntax) -> ExprSyntax {
            guard !dependencies.isEmpty else {
                return super.visit(node)
            }

            defer {
                dependencies = []
            }

            var items: [ArrayElementSyntax] = []
            for dep in dependencies {
                Logger.currentScope?.info("installing dependency: \(dep.value.url)")
                defer {
                    if dep.isModified {
                        Logger.currentScope?.warning("skipping dependency: \(dep.value.url)")
                    } else {
                        Logger.currentScope?.info("installed dependency: \(dep.value.url)")
                    }
                }
                let expr: ExprSyntax =
                    if let exists = dep.exists {
                        TriviaRemover()
                            .rewrite(exists)
                            .cast(ExprSyntax.self)
                    } else {
                        """
                        .package(url: "\(raw: dep.value.url)", from: "\(raw: dep.value.from)")
                        """
                    }
                items.append(ArrayElementSyntax(expression: expr).with(\.leadingTrivia, .newline))
            }

            if let elem = items.first {
                let trivia = elem.leadingTrivia.appending([.lineComment("// \(beginMarker)"), .newlines(1)])
                items[items.startIndex] = elem.with(\.leadingTrivia, trivia)
            }

            let elements = ArrayElementListSyntax {
                for element in node.elements {
                    element
                }
                for element in items {
                    element
                }
            }

            let endTrivia: Trivia = [
                .newlines(1),
                .spaces(4 * 2),
                .lineComment("// \(endMarker)"),
                .newlines(1),
                .spaces(4),
            ]
            return super.visit(
                node
                    .with(\.elements, elements)
                    .with(\.rightSquare.leadingTrivia, endTrivia)
            )
        }
    }

    private class TriviaRemover: SyntaxRewriter {
        override func visitAny(_ node: Syntax) -> Syntax? {
            node.trimmed
        }
    }
}
