name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          # renovate: datasource=github-runners
          - os: macos-26
            xcode: "/Applications/Xcode_26.4.1.app"
          - os: ubuntu-latest
            # renovate: datasource=docker
            container: swift:6.3

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
      - name: Cache package build dir
        uses: actions/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
            ${{ runner.os }}-spm-
      - name: Select Xcode
        if: ${{ matrix.xcode != null }}
        run: sudo xcode-select --switch "${{ matrix.xcode }}"
      - name: Run tests
        run: |
          swift test
